config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "sessions#new"

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  resources :tickets, only: %i[index new create show] do
    collection do
      get "export"
    end

    member do
      resources :comments
      patch "process", to: "ticket_status#start_process"
      patch "close", to: "ticket_status#close"
      patch "reset", to: "ticket_status#reset"
    end
  end

  resources :exports, only: %i[create]

  resources :sessions, only: %i[create destroy]

  resources :users, only: %i[new create]
  
  namespace :admin do
    resources :dashboards, only: %i[index]
    resources :agents, only: [] do
      member do
        patch "add", to: "agents#add_agent"
        patch "remove", to: "agents#remove_agent"
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :ticket

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_ticket, only: %i[index create]
  before_action :verify_ownership, only: %i[update delete]

  def index
  end

  def new; end

  def create
    comment = current_user.comments.new(permitted_params)

    if comment.save
      flash[:success] = "Comment posted"
      redirect_to ticket_path(@ticket)
    else
      flash[:warning] = comment.errors.full_messages.to_sentence
    end
  end

  private

  def permitted_params
    params.permit(:body).merge(ticket: @ticket)
  end

  def set_ticket
    @ticket = get_ticket(params[:id])
  end

  def verify_ownership
  end
end

app/views/comments/_base.html.erb
<div class="comment-container">
  <div class="card border-light mb-3">
    <div class="card-header">
      <h6>
        <%= comment.user.email %>
        <small><small class="text-muted"><%= format_time(comment.created_at) %></small></small>

        <% if comment.edited? %>
          <small><small><span class="float-right text-muted">Edited: <%= format_time(comment.updated_at) %></span></small></small>
        <% end %>
      </h6>
    </div>
    <div class="card-body">
      <p class="card-text"><%= comment.body %></p>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_tag comments_path do |form| %>
  <div class="input-group">
    <%= text_area_tag(:body, current_user.can_comment?(ticket) ? "" : "Comments disabled until a support agent comments",
      cols: 100, type:"text", id: "comment-textarea", class:"form-control", disabled: !current_user.can_comment?(ticket)) %>
    <div class="input-group-append">
      <% if current_user.agent? %>
        <button type="button" class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Comment</a>
          <% if ticket.closed? %>
            <%= link_to "Process", process_ticket_path(ticket), method: :patch, class: "dropdown-item" %>
            <%= link_to "Reset", reset_ticket_path(ticket), method: :patch, class: "dropdown-item" %>
          <% elsif ticket.processing? %>
            <%= link_to "Reset", reset_ticket_path(ticket), method: :patch, class: "dropdown-item" %>
            <%= link_to "Close", close_ticket_path(ticket), method: :patch, class: "dropdown-item" %>
          <% else %>
            <%= link_to "Process", process_ticket_path(ticket), method: :patch, class: "dropdown-item" %>
            <%= link_to "Close", close_ticket_path(ticket), method: :patch, class: "dropdown-item" %>
          <% end %>
        </div>
      <% end %>

      <%= submit_tag "comment", disabled: !current_user.can_comment?(ticket),
      class: "btn btn-outline-secondary d-flex align-items-center", id: "submit-comment-btn" %>
    </div>
  </div>
<% end %>