config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "sessions#new"

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  resources :tickets, only: %i[index new create show] do
    collection do
      get "export"
    end

    member do
      resources :comments
      patch "process", to: "ticket_status#start_process"
      patch "close", to: "ticket_status#close"
      patch "reset", to: "ticket_status#reset"
    end
  end

  resources :exports, only: %i[create]

  resources :sessions, only: %i[create destroy]

  resources :users, only: %i[new create]
  
  namespace :admin do
    resources :dashboards, only: %i[index]
    resources :agents, only: [] do
      member do
        patch "add", to: "agents#add_agent"
        patch "remove", to: "agents#remove_agent"
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :tickets, class_name: "Ticket", foreign_key: :customer
  has_many :handled_tickets, class_name: "Ticket", foreign_key: :closed_by
  has_many :comments

  validates_presence_of :password_digest
  validates :email, presence: true, uniqueness: true, case_sensitive: false

  scope :agents, -> { where(support_agent: true) }
  scope :customers, -> { where(admin: false, support_agent: false) }
  scope :admins, -> { where(admin: true) }

  def agent?
    admin? || support_agent?
  end

  def customer?
    !agent?
  end

  def can_export?
    agent?
  end

  concerning :Tickets do
    def can_comment?(ticket)
      ticket.commentable?(self)
    end

    def close(ticket)
      if agent?
        ticket.tap do |r|
          r.processing = false
          r.closed = true
          r.closed_at = DateTime.now
          r.closed_by = self
          r.save
        end
      end
    end

    def process(ticket)
      if agent?
        ticket.tap do |r|
          r.processing = true
          r.process_start_at = DateTime.now
          r.closed = false
          r.closed_at = nil
          r.save
        end
      end
    end

    def reset(ticket)
      if agent?
        ticket.tap do |r|
          r.processing = false
          r.process_start_at = nil
          r.closed = false
          r.closed_at = nil
          r.closed_by = nil
          r.save
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :reroute_valid_session, only: %i[new]
  before_action :reject_blank_auth_values, only: %i[create]

  def new; end

  def create
    @user = User.new(permitted_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Account creation successful"
      redirect_to tickets_path
    else
      redirect_to signup_path
      flash[:error] = @user.errors.full_messages.to_sentence
    end
  end

  private

  def permitted_params
    params.permit(:email, :password)
  end

  def set_user
    @user = current_user
  end
end

app/views/users/_signup_form.html.erb
<%= form_with(model: User, local: true) do |form| %>
  <%= form_tag users_path, { autocomplete: "off" } do |form| %>
    <div autocomplete="off" class="field">
      <%= label_tag :email %>
      <%= text_field_tag :email, nil, autofocus: true %>
    </div>
    <div autocomplete="off" class="field">
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </div>
    <div class="actions">
      <%= submit_tag "Sign up" %>
    </div>
  <% end %>
<% end %>

app/views/users/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Home", root_url%></li>
  <li class="breadcrumb-item active">Signup</li>
</ol>

<div class="signup-page page-content">
  <h1>Sign up</h1>

  <div class="form auth-form signup-form">
    <%= render 'signup_form' %>
  <div>

  <p>Already have an account? <%= link_to 'Login', login_path %> </p>
</div>

<div class="landing-background"></div>