config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "sessions#new"

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  resources :tickets, only: %i[index new create show] do
    collection do
      get "export"
    end

    member do
      resources :comments
      patch "process", to: "ticket_status#start_process"
      patch "close", to: "ticket_status#close"
      patch "reset", to: "ticket_status#reset"
    end
  end

  resources :exports, only: %i[create]

  resources :sessions, only: %i[create destroy]

  resources :users, only: %i[new create]
  
  namespace :admin do
    resources :dashboards, only: %i[index]
    resources :agents, only: [] do
      member do
        patch "add", to: "agents#add_agent"
        patch "remove", to: "agents#remove_agent"
      end
    end
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  before_action :verify_admin
  
  def index
    @agents = User.agents
    @customers = User.customers
  end
end

app/views/admin/dashboards/_user_group.html.erb
<ul class="list-group">
  <% users.each do |user| %>
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <%= user.email %>
      <% if user.agent? %>
        <span class="badge badge-primary badge-pill"><%= user.handled_tickets.size %> closed</span>
        <%= link_to "Remove agent", remove_admin_agent_path(user), 
          method: :patch, class: "btn btn-outline-primary btn-small" %>
      <% elsif user.customer? %>
        <%= link_to "Make agent", add_admin_agent_path(user), 
          method: :patch, class: "btn btn-outline-primary btn-small" %>
      <% end %>
    </li>
  <% end %>
  </li>
</ul>

app/views/admin/dashboards/index.html.erb
<h3>Manage users</h3>

<div class="container">
  <div class="row text-center">
    <div class="col-sm">
      <div class="users-list-container">
        <h5>Support agents</h5>
        <%= render "admin/dashboards/user_group", users: @agents%>
      </div>
    </div>
    <div class="col-sm">
      <div class="users-list-container">
        <h5>Customers</h5>
        <%= render "admin/dashboards/user_group", users: @customers%>
      </div>
    </div>
  </div>
</div>