config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "sessions#new"

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"

  resources :tickets, only: %i[index new create show] do
    collection do
      get "export"
    end

    member do
      resources :comments
      patch "process", to: "ticket_status#start_process"
      patch "close", to: "ticket_status#close"
      patch "reset", to: "ticket_status#reset"
    end
  end

  resources :exports, only: %i[create]

  resources :sessions, only: %i[create destroy]

  resources :users, only: %i[new create]
  
  namespace :admin do
    resources :dashboards, only: %i[index]
    resources :agents, only: [] do
      member do
        patch "add", to: "agents#add_agent"
        patch "remove", to: "agents#remove_agent"
      end
    end
  end
end

app/views/layouts/_flash.html.erb
<div class="alert-container center-block">
  <% flash.each do |type, msg| %>
    <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show container-fluid" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_footer.html.erb
<div class="footer-main fixed-bottom">
  <p class="copyright-text">
    ©<%= Time.now.year %> Q Help Desk. All Rights Reserved
  </p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <a class="navbar-brand" href="/">Q Help Desk</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="user_email_dropdown">
            <%= user.email %>
          </a>
          <div class="dropdown-menu .dropdown-menu-right bg-dark" aria-labelledby="navbarDropdown">
            
            <% if user.customer? %>
              <a class="nav-link" href=<%= tickets_path %> >My tickets</a>
            <% else %>
              <a class="nav-link" href=<%= tickets_path %> >All tickets</a>
              <a class="nav-link" href=<%= tickets_path(scope: "pending") %> >Pending tickets</a>
              <a class="nav-link" href=<%= tickets_path(scope: "processing") %> > In process tickets</a>
              <a class="nav-link" href=<%= tickets_path(scope: "closed") %> >All closed tickets</a>
              <a class="nav-link" href=<%= tickets_path(scope: "recently_closed") %> >Recently closed tickets</a>
            <% end %>

            <% if user.admin? %>
              <a class="nav-link" href=<%= admin_dashboards_path %> >Admin dashboard</a>
            <% end%>
            <div class="dropdown-divider"></div>
            <a class="nav-link" href=<%= logout_path %> >Logout</a>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href=<%= signup_path %> >Sign up</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href= "<%= login_path %>" >Login</a>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QHelpDesk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div className="main-wrapper">
      <%= render 'layouts/navbar', user: current_user %>

      <div class="main">
        <div class="page-container">
          <%= yield %>
        </div>
      </div>

      <%= render 'layouts/flash', flash: flash %>

    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>